export const WEATHER_FETCH_DATA_TODAY_SUCCESS = "WEATHER_FETCH_DATA_TODAY_SUCCESS";
export const WEATHER_FETCH_DATA_WEEK_SUCCESS = "WEATHER_FETCH_DATA_WEEK_SUCCESS";
export const WEATHER_FETCH_IS_START = "WEATHER_FETCH_IS_START";
export const WEATHER_FETCH_ERROR = "WEATHER_FETCH_ERROR";
